---
abstract: 'A client for the Instapaper Full API'
author:
  - 'Shun Takebayashi <shun@takebayashi.asia>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.3.0, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-Instapaper
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  WebService::Instapaper:
    file: lib/WebService/Instapaper.pm
    version: '0.01'
requires:
  LWP::Protocol::https: '0'
  OAuth::Lite: '0.21'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/takebayashi/p5-WebService-Instapaper/issues
  homepage: https://github.com/takebayashi/p5-WebService-Instapaper
  repository: git://github.com/takebayashi/p5-WebService-Instapaper.git
version: '0.01'
